//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 59 yılı aşkın bir süredir tek yetkili temsilcilikleri ile tıbbı cihaz satış, pazrlama ve servis konu  alanlarda kendini kabul ettirmiş olan Mikro Optik bu süre zarfında ürettiği birçok başarılı projeye imza atmıştır..
        /// </summary>
        internal static string AnaAltConten2 {
            get {
                return ResourceManager.GetString("AnaAltConten2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikro Optik uzman satış ve servis ekibi ile müşterilerine güçlü markalar ve kaliteli ürünlerle hizmet vermektedir..
        /// </summary>
        internal static string AnaAltConten3 {
            get {
                return ResourceManager.GetString("AnaAltConten3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler....
        /// </summary>
        internal static string AnaAltTitile1 {
            get {
                return ResourceManager.GetString("AnaAltTitile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunduğumuz Hizmetler....
        /// </summary>
        internal static string AnaAltTitile2 {
            get {
                return ResourceManager.GetString("AnaAltTitile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referanslar....
        /// </summary>
        internal static string AnaAltTitile3 {
            get {
                return ResourceManager.GetString("AnaAltTitile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devam....
        /// </summary>
        internal static string Devam {
            get {
                return ResourceManager.GetString("Devam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlk Sayfa.
        /// </summary>
        internal static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Sayfa.
        /// </summary>
        internal static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama.
        /// </summary>
        internal static string lblArama {
            get {
                return ResourceManager.GetString("lblArama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haberler.
        /// </summary>
        internal static string lblHaber {
            get {
                return ResourceManager.GetString("lblHaber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldiniz.
        /// </summary>
        internal static string lblHosgeldin {
            get {
                return ResourceManager.GetString("lblHosgeldin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kusursuz Hizmet Güvencesi....
        /// </summary>
        internal static string lblSlogan {
            get {
                return ResourceManager.GetString("lblSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İleri ».
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to « Geri.
        /// </summary>
        internal static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string ProductCatalog {
            get {
                return ResourceManager.GetString("ProductCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam.
        /// </summary>
        internal static string SearchMesaj1 {
            get {
                return ResourceManager.GetString("SearchMesaj1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adet kayıt bulundu..
        /// </summary>
        internal static string SearchMesaj2 {
            get {
                return ResourceManager.GetString("SearchMesaj2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt bulunamadı..
        /// </summary>
        internal static string SearchMesaj3 {
            get {
                return ResourceManager.GetString("SearchMesaj3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aradığınız sayfa bulunamadı..
        /// </summary>
        internal static string Title404 {
            get {
                return ResourceManager.GetString("Title404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam: .
        /// </summary>
        internal static string TotalPage {
            get {
                return ResourceManager.GetString("TotalPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Resimleri.
        /// </summary>
        internal static string UrunResimTitile {
            get {
                return ResourceManager.GetString("UrunResimTitile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana sayfaya dönmek için tıklayın..
        /// </summary>
        internal static string UygLink {
            get {
                return ResourceManager.GetString("UygLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatanın devam etmesi halinde bizimle iletişime geçiniz..
        /// </summary>
        internal static string UygMesaj {
            get {
                return ResourceManager.GetString("UygMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama Hatası.
        /// </summary>
        internal static string UygTitle {
            get {
                return ResourceManager.GetString("UygTitle", resourceCulture);
            }
        }
    }
}
